**Zadanie 1**

In [2]:
import pandas as pd
import numpy as np
data = pd.read_csv('president_heights.csv')
heights = np.array(data['height(cm)'])
print(heights)


[189 170 189 163 183 171 185 168 173 183 173 173 175 178 183 193 178 173
 174 183 183 168 170 178 182 180 183 178 182 188 175 179 183 193 182 183
 177 185 188 188 182 185]


In [6]:
print("Mean height:       ", np.mean(heights))
print("Standard deviation:", np.std(heights))
print("Minimum height:    ", np.min(heights))
print("Maximum height:    ", np.max(heights))


Mean height:        179.73809523809524
Standard deviation: 6.931843442745892
Minimum height:     163
Maximum height:     193


In [12]:
print("25th percentile:   ", np.percentile(  heights,25) )
print("Median:            ", np.percentile(  heights,50) )
print("75th percentile:   ", np.percentile(  heights,75) )


25th percentile:    174.25
Median:             182.0
75th percentile:    183.0


**Zadanie 2**


In [24]:
data_2=np.genfromtxt('Zadanie_2.csv', delimiter=';')    

array([[  1.,   2.,  15., -59.,   9.,   3.,  75.,   6.,   7.,   1.],
       [  0.,   5.,   0.,   4.,   6.,  16.,  44.,   7.,   1.,   1.],
       [  7.,  14.,   3., -10.,   9.,  15.,  73.,   8.,   2.,   9.],
       [  1.,   5.,  15., -54.,   5.,  15.,  35.,   8.,   6.,   4.],
       [  0.,   8.,   5., -18.,   7.,  16.,  91.,   6.,   7.,   9.],
       [  7.,  18.,  23., -90.,   4.,   8.,  31.,   0.,   1.,   7.],
       [  2.,   8.,  20., -72.,   4.,   1.,  91.,   9.,   4.,   4.],
       [  4.,  12.,  18., -65.,   6.,   9.,  76.,   4.,   9.,   9.],
       [  7.,  15.,  13., -52.,   5.,   7.,  54.,   2.,   7.,   0.],
       [  2.,   9.,  15., -56.,   6.,   1.,  98.,   4.,   8.,   4.]])

In [27]:
w,v=np.linalg.eig(data_2) 
print(w) #wartości
print(v) #wektory

[104.34960192 +0.j         -23.35660516+18.84992811j
 -23.35660516-18.84992811j  15.92989017 +0.j
  -4.99456452 +0.j           0.35205717 +5.80125175j
   0.35205717 -5.80125175j  -1.03383491 +0.j
   3.87900166 +1.42651533j   3.87900166 -1.42651533j]
[[-0.29000475+0.j         -0.07545445+0.07743149j -0.07545445-0.07743149j
  -0.03544485+0.j          0.42681634+0.j         -0.22172831-0.29869259j
  -0.22172831+0.29869259j  0.41343726+0.j         -0.28670255+0.21891569j
  -0.28670255-0.21891569j]
 [-0.24163153+0.j          0.41229621+0.09197324j  0.41229621-0.09197324j
   0.45873475+0.j         -0.27056206+0.j         -0.01331344+0.1422557j
  -0.01331344-0.1422557j  -0.31591047+0.j          0.41954481-0.10561864j
   0.41954481+0.10561864j]
 [-0.41060573+0.j          0.37509638-0.00960818j  0.37509638+0.00960818j
   0.64067986+0.j         -0.37967609+0.j         -0.60525232+0.j
  -0.60525232-0.j          0.6457768 +0.j          0.63631555+0.j
   0.63631555-0.j        ]
 [-0.18899971+0.j   

In [18]:
tablica=np.array([1,2,3,4,5,6,7,8,9])
indeces=[0,3,7]
tablica[indeces]

array([1, 4, 8])

**Zadanie 3**

In [29]:
import numpy as np
import pandas as pd

# use pandas to extract rainfall inches as a NumPy array
rainfall = pd.read_csv('Seattle2014.csv')['PRCP'].values
inches = rainfall / 254.0  # 1/10mm -> inches
inches.shape

(365,)

array([ True,  True,  True, False, False, False,  True, False,  True,
        True, False, False,  True,  True, False,  True, False, False,
        True,  True, False, False, False, False, False,  True,  True,
        True,  True, False, False,  True,  True, False, False, False,
       False,  True, False,  True, False,  True, False, False, False,
        True,  True,  True,  True,  True, False, False,  True,  True,
        True,  True, False, False, False, False, False, False, False,
        True, False, False, False, False, False,  True,  True,  True,
       False,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True, False, False,  True, False,
        True,  True,  True,  True,  True, False, False,  True, False,
        True,  True, False, False, False, False,  True, False, False,
        True, False, False,  True, False,  True,  True, False,  True,
       False, False,  True, False,  True,  True,  True, False,  True,
       False,  True,

In [73]:
print("Number days without rain:      ", np.sum(inches<=0) )
print("Number days with rain:         ", np.sum(inches>0) )
print("Days with more than 0.5 inches:", np.sum(inches > 0.5))
print("Rainy days with < 0.2 inches  :", np.sum(inches[inches>=0]<=0.2) )


Number days without rain:       215
Number days with rain:          150
Days with more than 0.5 inches: 37
Rainy days with < 0.2 inches  : 290


In [ ]:
# 0.1881

In [46]:
print("Median precip on rainy days in 2014 (inches):   ", np.median(inches[inches > 0]))
print("Median precip on summer days in 2014 (inches):  ", np.median(inches[172:262]) )
print("Maximum precip on summer days in 2014 (inches): ", np.max(inches[172:262]))
print("Median precip on non-summer rainy days (inches):", np.max(inches[172:262]))


Median precip on rainy days in 2014 (inches):    0.19488188976377951
Median precip on summer days in 2014 (inches):   0.0
Maximum precip on summer days in 2014 (inches):  0.8503937007874016
Median precip on non-summer rainy days (inches): 0.8503937007874016


**Zadanie 4**

In [47]:
A = [0,3,2,5]
B = [0,3,1,4]

$A+B$

In [49]:
np.add(A,B)

array([0, 6, 3, 9])

$B-A$

In [61]:
np.subtract(B,A)

array([ 0,  0, -1, -1])

$4 \cdot A $

In [59]:
np.dot(A,4)

array([ 0, 12,  8, 20])

$|B|$

In [62]:
np.linalg.norm(B)

5.0990195135927845